### ISSUE TITLE
谁说没人看啊？这半年以来这份代码加了些什么模块啊？有哪些改进啊？

### ISSUE THREAD

**Issue by icelostnfound** [hust-IR2/ihealth#2]
我看加入了TBB，看来在视觉模块加了些新东西啊。。可以把毛伟拉进来，这样更像是共同开发，不过工作以后还是用SVN比较多，没钱买private，那你就在实验室本地搭个repository啊，用SVN客户端做update/commit/merge！

**Comment by senlin-hust** [comment]
https://www.cnblogs.com/mq0036/p/5250198.html，自个搭个SVN本地服务器吧！免得到时候被英特博起诉你泄密公司绝密资料！

**Comment by icelostnfound** [comment]
自个搭个SVN本地服务器吧！免得到时候被英特博起诉你泄密公司绝密资料！https://www.cnblogs.com/mq0036/p/5250198.html，

**Comment by volcanoh** [comment]
git服务器也挺容易的，不想弄，代码公开似乎也没有啥影响~~~毛还在休假中……
